/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package app

import com.typesafe.scalalogging.LazyLogging

object App extends LazyLogging {
  import logger._

  def main(args: Array[String]): Unit = {
    debug(greeting)
    info(greeting)
    warn(greeting)
    error(greeting)
  }

  def greeting: String = "Hello, world!"
}
